[tool.poetry]
name = "sqloxide"
version = "0.1.0"
description = ""
authors = ["Will Eaton <me@wseaton.com>"]
build = "build.py"

[tool.poetry.dependencies]
python = ">=3.7,<4.0"
graphviz = "^0.15"

[tool.poetry.dev-dependencies]
setuptools-rust = "^0.11.5"
pytest = "^6.1.2"
black = "^20.8b1"
isort = "^5.6.4"
ipython = "^7.19.0"

[build-system]
requires = ["poetry-core>=1.0.0", "setuptools>=41.0.0", "wheel", "setuptools_rust>=0.10.2"]
build-backend = "poetry.core.masonry.api"
